// node_modules/.pnpm/aria-attributes@2.0.1/node_modules/aria-attributes/index.js
type ariaAttributes = [
  "aria-activedescendant",
  "aria-atomic",
  "aria-autocomplete",
  "aria-busy",
  "aria-checked",
  "aria-colcount",
  "aria-colindex",
  "aria-colspan",
  "aria-controls",
  "aria-current",
  "aria-describedby",
  "aria-details",
  "aria-disabled",
  "aria-dropeffect",
  "aria-errormessage",
  "aria-expanded",
  "aria-flowto",
  "aria-grabbed",
  "aria-haspopup",
  "aria-hidden",
  "aria-invalid",
  "aria-keyshortcuts",
  "aria-label",
  "aria-labelledby",
  "aria-level",
  "aria-live",
  "aria-modal",
  "aria-multiline",
  "aria-multiselectable",
  "aria-orientation",
  "aria-owns",
  "aria-placeholder",
  "aria-posinset",
  "aria-pressed",
  "aria-readonly",
  "aria-relevant",
  "aria-required",
  "aria-roledescription",
  "aria-rowcount",
  "aria-rowindex",
  "aria-rowspan",
  "aria-selected",
  "aria-setsize",
  "aria-sort",
  "aria-valuemax",
  "aria-valuemin",
  "aria-valuenow",
  "aria-valuetext",
  "role"
];

// node_modules/.pnpm/html-element-attributes@3.1.0/node_modules/html-element-attributes/index.js
type htmlElementAttributes = {
  "*": [
    "accesskey",
    "autocapitalize",
    "autofocus",
    "class",
    "contenteditable",
    "dir",
    "draggable",
    "enterkeyhint",
    "hidden",
    "id",
    "inputmode",
    "is",
    "itemid",
    "itemprop",
    "itemref",
    "itemscope",
    "itemtype",
    "lang",
    "nonce",
    "slot",
    "spellcheck",
    "style",
    "tabindex",
    "title",
    "translate"
  ],
  a: [
    "charset",
    "coords",
    "download",
    "href",
    "hreflang",
    "name",
    "ping",
    "referrerpolicy",
    "rel",
    "rev",
    "shape",
    "target",
    "type"
  ],
  applet: [
    "align",
    "alt",
    "archive",
    "code",
    "codebase",
    "height",
    "hspace",
    "name",
    "object",
    "vspace",
    "width"
  ],
  area: [
    "alt",
    "coords",
    "download",
    "href",
    "hreflang",
    "nohref",
    "ping",
    "referrerpolicy",
    "rel",
    "shape",
    "target",
    "type"
  ],
  audio: [
    "autoplay",
    "controls",
    "crossorigin",
    "loop",
    "muted",
    "preload",
    "src"
  ],
  base: ["href", "target"],
  basefont: ["color", "face", "size"],
  blockquote: ["cite"],
  body: ["alink", "background", "bgcolor", "link", "text", "vlink"],
  br: ["clear"],
  button: [
    "disabled",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "name",
    "type",
    "value"
  ],
  canvas: ["height", "width"],
  caption: ["align"],
  col: ["align", "char", "charoff", "span", "valign", "width"],
  colgroup: ["align", "char", "charoff", "span", "valign", "width"],
  data: ["value"],
  del: ["cite", "datetime"],
  details: ["open"],
  dialog: ["open"],
  dir: ["compact"],
  div: ["align"],
  dl: ["compact"],
  embed: ["height", "src", "type", "width"],
  fieldset: ["disabled", "form", "name"],
  font: ["color", "face", "size"],
  form: [
    "accept",
    "accept-charset",
    "action",
    "autocomplete",
    "enctype",
    "method",
    "name",
    "novalidate",
    "target"
  ],
  frame: [
    "frameborder",
    "longdesc",
    "marginheight",
    "marginwidth",
    "name",
    "noresize",
    "scrolling",
    "src"
  ],
  frameset: ["cols", "rows"],
  h1: ["align"],
  h2: ["align"],
  h3: ["align"],
  h4: ["align"],
  h5: ["align"],
  h6: ["align"],
  head: ["profile"],
  hr: ["align", "noshade", "size", "width"],
  html: ["manifest", "version"],
  iframe: [
    "align",
    "allow",
    "allowfullscreen",
    "allowpaymentrequest",
    "allowusermedia",
    "frameborder",
    "height",
    "loading",
    "longdesc",
    "marginheight",
    "marginwidth",
    "name",
    "referrerpolicy",
    "sandbox",
    "scrolling",
    "src",
    "srcdoc",
    "width"
  ],
  img: [
    "align",
    "alt",
    "border",
    "crossorigin",
    "decoding",
    "height",
    "hspace",
    "ismap",
    "loading",
    "longdesc",
    "name",
    "referrerpolicy",
    "sizes",
    "src",
    "srcset",
    "usemap",
    "vspace",
    "width"
  ],
  input: [
    "accept",
    "align",
    "alt",
    "autocomplete",
    "checked",
    "dirname",
    "disabled",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "height",
    "ismap",
    "list",
    "max",
    "maxlength",
    "min",
    "minlength",
    "multiple",
    "name",
    "pattern",
    "placeholder",
    "readonly",
    "required",
    "size",
    "src",
    "step",
    "type",
    "usemap",
    "value",
    "width"
  ],
  ins: ["cite", "datetime"],
  isindex: ["prompt"],
  label: ["for", "form"],
  legend: ["align"],
  li: ["type", "value"],
  link: [
    "as",
    "charset",
    "color",
    "crossorigin",
    "disabled",
    "href",
    "hreflang",
    "imagesizes",
    "imagesrcset",
    "integrity",
    "media",
    "referrerpolicy",
    "rel",
    "rev",
    "sizes",
    "target",
    "type"
  ],
  map: ["name"],
  menu: ["compact"],
  meta: ["charset", "content", "http-equiv", "media", "name", "scheme"],
  meter: ["high", "low", "max", "min", "optimum", "value"],
  object: [
    "align",
    "archive",
    "border",
    "classid",
    "codebase",
    "codetype",
    "data",
    "declare",
    "form",
    "height",
    "hspace",
    "name",
    "standby",
    "type",
    "typemustmatch",
    "usemap",
    "vspace",
    "width"
  ],
  ol: ["compact", "reversed", "start", "type"],
  optgroup: ["disabled", "label"],
  option: ["disabled", "label", "selected", "value"],
  output: ["for", "form", "name"],
  p: ["align"],
  param: ["name", "type", "value", "valuetype"],
  pre: ["width"],
  progress: ["max", "value"],
  q: ["cite"],
  script: [
    "async",
    "charset",
    "crossorigin",
    "defer",
    "integrity",
    "language",
    "nomodule",
    "referrerpolicy",
    "src",
    "type"
  ],
  select: [
    "autocomplete",
    "disabled",
    "form",
    "multiple",
    "name",
    "required",
    "size"
  ],
  slot: ["name"],
  source: ["height", "media", "sizes", "src", "srcset", "type", "width"],
  style: ["media", "type"],
  table: [
    "align",
    "bgcolor",
    "border",
    "cellpadding",
    "cellspacing",
    "frame",
    "rules",
    "summary",
    "width"
  ],
  tbody: ["align", "char", "charoff", "valign"],
  td: [
    "abbr",
    "align",
    "axis",
    "bgcolor",
    "char",
    "charoff",
    "colspan",
    "headers",
    "height",
    "nowrap",
    "rowspan",
    "scope",
    "valign",
    "width"
  ],
  textarea: [
    "autocomplete",
    "cols",
    "dirname",
    "disabled",
    "form",
    "maxlength",
    "minlength",
    "name",
    "placeholder",
    "readonly",
    "required",
    "rows",
    "wrap"
  ],
  tfoot: ["align", "char", "charoff", "valign"],
  th: [
    "abbr",
    "align",
    "axis",
    "bgcolor",
    "char",
    "charoff",
    "colspan",
    "headers",
    "height",
    "nowrap",
    "rowspan",
    "scope",
    "valign",
    "width"
  ],
  thead: ["align", "char", "charoff", "valign"],
  time: ["datetime"],
  tr: ["align", "bgcolor", "char", "charoff", "valign"],
  track: ["default", "kind", "label", "src", "srclang"],
  ul: ["compact", "type"],
  video: [
    "autoplay",
    "controls",
    "crossorigin",
    "height",
    "loop",
    "muted",
    "playsinline",
    "poster",
    "preload",
    "src",
    "width"
  ]
};

type globalAttributes = [...htmlElementAttributes['*'], ...ariaAttributes];

// Custom
type elementAttributes<E> = [...globalAttributes, ...(
  E extends keyof htmlElementAttributes ? htmlElementAttributes[E] : []
)];

export type Attributes<E> = Record<elementAttributes<E>[number], string>